#!/bin/bash
#PBS -A UQ-SCI-BiolSci
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=15:mem=60GB
#PBS -N nucleotide_diversity

cd $PBS_O_WORKDIR

#setting the job population bam paths list
BAMS=/30days/uqakaur3/recombinantpop/arraylists/bam-paths.txt

#setting the target regions (format is contig:start-end)
REGIONS=/30days/uqakaur3/pilot/region/sorted_linkagegroup_one.txt

#setting reference genome and its location
REF=/90days/uqakaur3/Reference/SPD_CN1K_CtgRN.fasta

module load angsd

#without filters

angsd -P 15 -dosaf 1 -doThetas 1 -GL 2 -doMajorMinor 1 -underFlowProtect 1 \
	-anc $REF \
	-b $BAMS -rf $REGIONS \
	-pest recombinant_lg_one_sfs.dsfs \
	-out recombinant_thetas

#run with filters as well



#replace bampaths
#D01_bam-paths.txt
#H01_bam-paths.txt
#gravitropicbam-paths.txt
#agravitropicbam-paths.txt
#bam-paths.txt 
