#!/bin/bash
#PBS -A UQ-SCI-BiolSci
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=15:mem=60GB
#PBS -N thetastat

cd $PBS_O_WORKDIR

/home/uqakaur3/angsd/misc/thetaStat do_stat recombinant_thetas.thetas.idx


