#!/bin/bash
#PBS -A UQ-SCI-BiolSci
#PBS -l walltime=04:00:00
#PBS -l select=1:ncpus=15:mem=60GB
#PBS -N sliding window analysis

cd $PBS_O_WORKDIR

/home/uqakaur3/angsd/misc/thetaStat do_stat /30days/uqakaur3/thetas/grav/recombinant_grav.thetas.idx -win 4000 -step 800 -outnames grav.thetas.windows
