#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=100GB
#PBS -l jobfs=100GB
#PBS -q normal
#PBS -P ht96
#PBS -l walltime=7:00:00
#PBS -l storage=scratch/ht96+gdata/ht96


/home/564/ak2993/angsd/misc/realSFS fst stats2 /g/data/ht96/Avneet_UQ/manuscript/fst/fst_index/LG_1_H01.D01.fst.idx -win 10000 -step 1000 > /g/data/ht96/Avneet_UQ/manuscript/fst/fst_sliding_window/sliding_win_LG_1_H01.D01_fst.txt

