#!/bin/bash
#PBS -A UQ-SCI-BiolSci
#PBS -l walltime=00:08:00
#PBS -l select=1:ncpus=1:mem=0.5GB
#PBS -N align-stat-array
#PBS -J 1-50
set -e 
set -u 
set -o pipefail

#changing to the temporary job directory
cd ${TMPDIR}

#loading the programs
module load samtools

#setting the sample list
SAMPLELIST=/home/uqralls1/gravitropicinds.txt

#setting the sample from the job array
SAMPLE=$(cat ${SAMPLELIST} | tail -n +${PBS_ARRAY_INDEX} | head -1)

#copying the necessary files to the temporary job directory
cp /30days/uqralls1/${SAMPLE}_sorted.bam ${TMPDIR}

#running samtools flagstat
samtools flagstat ${TMPDIR}/${SAMPLE}_sorted.bam &> ${TMPDIR}/${SAMPLE}_stats.txt

#copying the stats file from the job temporary directory back to the results directory
cp ${TMPDIR}/${SAMPLE}_stats.txt /30days/uqralls1/GravitropicResults/Stats/
