#!/bin/bash
#PBS -l ncpus=10
#PBS -l mem=100GB
#PBS -l jobfs=110GB
#PBS -q normal
#PBS -P ht96
#PBS -l walltime=6:00:00
#PBS -l storage=scratch/ht96+gdata/ht96



DIR=/g/data/ht96/Avneet_UQ/manuscript/bam_paths

REGION=/g/data/ht96/Avneet_UQ/manuscript/fst/intersect/intersect_LG_1.chrs

ANGSD=/home/564/ak2993/angsd/

ANC=/g/data/ht96/Avneet_UQ/reference/SPD_CN1K_CtgRN.fasta

SITES=/g/data/ht96/Avneet_UQ/manuscript/fst/intersect/intersect_LG_1.txt


for POP in D01 H01

do

    echo $POP

    PERCENT_IND=0.5 #filter : will keep SNP with at least one read for this percentage of individuals
    MAX_DEPTH_FACTOR=4 #filter : will keep SNP with less than X time the no of individuals total coverage
    MIN_DEPTH=1

    N_IND=$(wc -l $DIR/$POP'_bams.txt' | cut -d " " -f 1)
    MIN_IND_FLOAT=$(echo "($N_IND * $PERCENT_IND)"| bc -l)
    MIN_IND=${MIN_IND_FLOAT%.*}
    MAX_DEPTH=$(echo "($N_IND * $MAX_DEPTH_FACTOR)" |bc -l)

    ${ANGSD}/angsd -b $DIR/$POP'_bams.txt' -anc $ANC -rf $REGION -out /g/data/ht96/Avneet_UQ/manuscript/dxy/mafs/$POP'_LG_1' \
                   -remove_bads 1 -minInd $MIN_IND -setMaxDepth $MAX_DEPTH -setMinDepthInd $MIN_DEPTH \
                   -minMapQ 30 -minQ 20 -doCounts 1 \
                   -GL 1 -doMajorMinor 5 -doMaf 1 -skipTriallelic 1  -sites $SITES -dumpCounts 2 -nThreads 10 -underFlowProtect 1
done

